services:
  runner:
    build: .
    restart: always
    env_file: .env
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.35"
          memory: 300M
        reservations:
          cpus: "0.25"
          memory: 128M
